### ISSUE TITLE
README order is odd

### ISSUE THREAD

**Issue by skade** [Sean1708/rusty-cheddar#15]
Although the README states upfront that a nightly compiler is necessary for the following steps, then introduces steps that need nightly, then introduces steps for working with stable.

I think it should be the other way around: "I have a stable compiler from the website installed, how do I use it".

In generall, I also think that `#[plugin()]` usage for tools like this should be avoided.

**Comment by Sean1708** [comment]
[How's this?](https://github.com/Sean1708/rusty-cheddar/commit/88312bab398d74b1edfccfd2457a588ed4bf142f)

> In generall, I also think that `#[plugin()]` usage for tools like this should be avoided.

I think it's perfectly valid way to work (if a bit of an abuse of the lint system) and that users should at least be aware of the possibility of using it this way.
