### ISSUE TITLE
Header ifdef guard should filter out illegal characters

### ISSUE THREAD

**Issue by jgallagher** [Sean1708/rusty-cheddar#29]
The ifdef guard is currently defined as

```rust
"#ifndef cheddar_generated_{0}_h"
```

(likewise for the next line) where `{0}` is filled in with the header filename. For typical header filenames, this creates preprocessor tokens that look like `cheddar_generated_filename.h_h`, but `.` is not a legal preprocessor identifier character (clang under OS X gives a warning about "extra tokens following an identifier", pointing to the `.`).

**Comment by Sean1708** [comment]
Thanks for letting me know, that should be fixed now and I've done a `v0.3.1` release for you. Could you check that it has worked then close this issue if it has please.

**Comment by jgallagher** [comment]
Yep, thanks!
